### ISSUE TITLE
Help change folder icon

### ISSUE THREAD

**Issue by thenoobtester** [heralight/GlibSortFileNameHackLibrary#1]
Hi,

this is a very interesting idea and way of doing things. I'm trying to change a folder's icon using the same trick but it doesn't work.

I identified the function (get_icon_name) which returns the icon name, https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/glocalfileinfo.c line 1735. So I created a modified get_icon_name function (see attached, it's incomplete just to test the hook).[geticonname.zip](https://github.com/heralight/GlibSortFileNameHackLibrary/files/7260392/geticonname.zip)

And I load it using LD_PRELOAD but it has no effect.

Do you think you could point me in the right direction just to get the modified function get injected, then I'll figure out the rest?

Thank you

PS:Je viens juste de remarquer que votre blog était en :fr:  :+1:

**Comment by heralight** [comment]
Hi,
In the first place, did you success to run the test from my repository ?
If yes, then recheck that you match the exact method in your system, perhaps have different version.
If not, then sorry but I can't help more, it was 6 years old and I don't play with C/C++ anymore.

Best regards,

Alexandre
